import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./component/Navbar";
import Footer from "./component/Footer";
import { configs } from "./configs";
import GoogleTagManager from "./_analytics/GoogleTagManager";
import GoogleTagId from "./_analytics/GoogleTagId";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Gloitel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const { google } = configs;
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
        {/* {nodeEnv === production && <GoogleTagManager GTM_ID={google.tagId} />} */}

        <script async src="https://apis.google.com/js/platform.js"></script>
        <GoogleTagManager GTM_ID={google.tagId} />
        <GoogleTagId GTAG={google.gtmId} />
        {/* <GoogleAdsTag adsId={google.analyticsId} /> */}
      </body>
    </html>
  );
}
