import "./globals.css";
import Navbar from "./component/Navbar";
import Footer from "./component/Footer";
import { DM_Sans } from "next/font/google";

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--framer-font-family",
});

export const metadata = {
  title: "Gloitel",
  description: "Generated by create next app",
  icons: {
    icon: "https://framerusercontent.com/images/Z2Vm6MYJmpRUiSTorzNcqzedmQ.png", // 👈 Path relative to /public folder
  },
};
export default function RootLayout({ children }) {
  return (
    <html lang="en" data-scroll-behavior="smooth">
      <head>
        <link
          rel="icon"
          href="https://framerusercontent.com/images/Z2Vm6MYJmpRUiSTorzNcqzedmQ.png"
        />
        <title>Gloitel</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body className={`${dmSans.variable} antialiased`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
