import "./globals.css";
import Navbar from "./component/Navbar";
import Footer from "./component/Footer";
import { configs } from "./configs";
import GoogleTagManager from "./_analytics/GoogleTagManager";
import GoogleTagId from "./_analytics/GoogleTagId";
import CustomCursor from "./component/CustomCursor";
import { DM_Sans } from "next/font/google";
import { Toaster } from "react-hot-toast";

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--framer-font-family",
});

export const metadata = {
  title: "Gloitel",
  description: "Generated by create next app",
  icons: {
    icon: "https://res.cloudinary.com/dsqu6pi0d/image/upload/v1762927663/Gloitel/favicon.avif", // 👈 Path relative to /public folder
  },
};
export default function RootLayout({ children }) {
  const { google } = configs;
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link
          rel="icon"
          href="https://res.cloudinary.com/dsqu6pi0d/image/upload/v1762927663/Gloitel/favicon.avif"
        />
        <title>Gloitel</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body className={`${dmSans.variable} antialiased overflow-x-hidden `}>
        <CustomCursor />
        <Navbar />
        {children}
        <Footer />
        {/* {nodeEnv === production && <GoogleTagManager GTM_ID={google.tagId} />} */}

        <script async src="https://apis.google.com/js/platform.js"></script>
        {/* <GoogleTagManager GTM_ID={google.tagId} /> */}
        <GoogleTagId GTAG={google.gtmId} />
        {/* <GoogleAdsTag adsId={google.analyticsId} /> */}
        <Toaster position="bottom-right" />
      </body>
    </html>
  );
}
